name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  commit-lint:
    name: Semantic Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 200
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
      - name: Check commit titles
        run: |
          npm install @commitlint/cli @commitlint/config-conventional
          npx commitlint --verbose --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }}

  eslint:
    name: ESLint - Reviewdog
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: '--ext vue --ext js --ext ts --ext json .'
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

  black:
    name: Black - Reviewdog
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/checkout@v3
      - run: pip install black-with-tabs
      - uses: reviewdog/action-black@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

  semgrep:
    name: Semgrep Rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Download Semgrep rules
        run: git clone --depth 1 https://github.com/frappe/semgrep-rules.git frappe-semgrep-rules
      - name: Run Semgrep rules
        run: |
          pip install semgrep==0.97.0
          semgrep ci --config ./frappe-semgrep-rules/rules --config r/python.lang.correctness
